name: uvc
description: A Dart package for controlling UVC compliant webcams on macOS and Windows.
version: 1.2.0
homepage: https://github.com/larryaasen/uvc
repository: https://github.com/larryaasen/uvc

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  convert: ^3.1.1
  equatable: ^2.0.5
  ffi: ^1.2.1
  libusb: ^0.3.23+2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.7
